# Generated by Django 4.2 on 2024-04-08 17:43

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('functionalStrat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bossstrat',
            name='description',
            field=models.CharField(default='Boss Description Here', max_length=1000),
        ),
        migrations.AddField(
            model_name='bossstrat',
            name='ertNote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bossstrat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bossstrat',
            name='roster',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bossstrat',
            name='title',
            field=models.CharField(default='Boss Name Here', max_length=200),
        ),
        migrations.AddField(
            model_name='bossstrat',
            name='weakaura',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bossstrat',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='functionalStrat.boss')),
            ],
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('raid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='functionalStrat.raid')),
            ],
        ),
        migrations.AddField(
            model_name='boss',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='functionalStrat.bossstrat', unique=True),
        ),
    ]
