# Generated by Django 4.2 on 2024-04-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functionalStrat', '0002_boss_bossstrat_description_bossstrat_ertnote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='strategy',
        ),
        migrations.AddField(
            model_name='bossstrat',
            name='boss',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='functionalStrat.boss'),
        ),
    ]
