# Generated by Django 4.2 on 2024-04-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functionalStrat', '0004_alter_expansion_raid_alter_raid_boss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expansion',
            name='raid',
        ),
        migrations.RemoveField(
            model_name='raid',
            name='boss',
        ),
        migrations.AddField(
            model_name='boss',
            name='raid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='functionalStrat.raid'),
        ),
        migrations.AddField(
            model_name='raid',
            name='expansion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='functionalStrat.expansion'),
        ),
    ]
